Repository AY2021S1-CS2103T-W17-4/tp, pull requests merged in 2020-11, with the labels that each got.

#174 Bug fixes about card selection in list panels and its content view
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/AddContactCommand.java
  src/main/java/seedu/address/logic/commands/AddJournalEntryCommand.java
  src/main/java/seedu/address/logic/commands/CommandResult.java
  src/main/java/seedu/address/logic/commands/EditContactCommand.java
  src/main/java/seedu/address/logic/commands/EditJournalEntryCommand.java
  src/main/java/seedu/address/logic/commands/ViewJournalEntryCommand.java
  src/main/java/seedu/address/logic/commands/ViewPersonCommand.java
  src/main/java/seedu/address/ui/EntryContent.java
  src/main/java/seedu/address/ui/EntryListPanel.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/PersonListPanel.java
  src/test/java/seedu/address/logic/commands/EditContactCommandTest.java
Labels: severity.High, type.Bug

#214 Fix edited contact in entry
  src/main/java/seedu/address/logic/commands/EditContactCommand.java
  src/main/java/seedu/address/model/Journal.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/journal/Entry.java
  src/main/java/seedu/address/model/journal/UniqueEntryList.java
  src/test/java/seedu/address/logic/commands/AddAliasCommandTest.java
  src/test/java/seedu/address/logic/commands/AddContactCommandTest.java
  src/test/java/seedu/address/logic/commands/AddJournalEntryCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteAliasCommandTest.java
  src/test/java/seedu/address/logic/commands/EditContactCommandTest.java
  src/test/java/seedu/address/model/JournalTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/journal/EntryTest.java
  src/test/java/seedu/address/storage/JsonAdaptedEntryTest.java
  src/test/java/seedu/address/storage/JsonSerializableJournalTest.java
  src/test/java/seedu/address/testutil/EntryBuilder.java
Labels: severity.High, type.Bug

#215 Fix UG bugs
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/images/Ui-contacts.png
  docs/images/Ui-dashboard.png
  docs/images/Ui-journal.png
  docs/index.md
  src/main/java/seedu/address/model/journal/Date.java
Labels: severity.High, type.Bug

#216 Fix duplicate name persons
  src/main/java/seedu/address/logic/commands/AddContactCommand.java
  src/main/java/seedu/address/logic/commands/EditContactCommand.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/UniquePersonList.java
  src/test/java/seedu/address/logic/commands/AddAliasCommandTest.java
  src/test/java/seedu/address/logic/commands/AddContactCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/AddContactCommandTest.java
  src/test/java/seedu/address/logic/commands/AddJournalEntryCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteAliasCommandTest.java
  src/test/java/seedu/address/logic/commands/EditContactCommandTest.java
  src/test/java/seedu/address/model/person/UniquePersonListTest.java
Labels: type.Bug

#217 Add Portfolio Page
  docs/AboutUs.md
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/team/joshualiangxy.md
  docs/team/lingy12.md
Labels: priority.High, type.Task

#222 Add more journal entries for demo
  src/main/java/seedu/address/model/util/SampleDataUtil.java
Labels: priority.Low, type.Enhancement

#231 Update string format
  docs/AboutUs.md
  docs/UserGuide.md
  docs/images/UGExamples/addjournalExample2.png
  docs/team/jazerler.md
  docs/team/joshualiangxy.md
  docs/team/nauw1010.md
  src/main/java/seedu/address/model/journal/Entry.java
  src/main/java/seedu/address/model/person/Person.java
Labels: type.Enhancement

#233 Message usage to use alias
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/AddAliasCommand.java
  src/main/java/seedu/address/logic/commands/AddContactCommand.java
  src/main/java/seedu/address/logic/commands/AddJournalEntryCommand.java
  src/main/java/seedu/address/logic/commands/ChangeThemeCommand.java
  src/main/java/seedu/address/logic/commands/CheckScheduleCommand.java
  src/main/java/seedu/address/logic/commands/ClearAddressBookCommand.java
  src/main/java/seedu/address/logic/commands/ClearJournalCommand.java
  src/main/java/seedu/address/logic/commands/DeleteAliasCommand.java
  src/main/java/seedu/address/logic/commands/DeleteContactCommand.java
  src/main/java/seedu/address/logic/commands/DeleteJournalEntryCommand.java
  src/main/java/seedu/address/logic/commands/EditContactCommand.java
  src/main/java/seedu/address/logic/commands/EditJournalEntryCommand.java
  src/main/java/seedu/address/logic/commands/ExitCommand.java
  src/main/java/seedu/address/logic/commands/FindContactCommand.java
  src/main/java/seedu/address/logic/commands/FindJournalEntryCommand.java
  src/main/java/seedu/address/logic/commands/HelpCommand.java
  src/main/java/seedu/address/logic/commands/ListContactCommand.java
  src/main/java/seedu/address/logic/commands/ListJournalEntryCommand.java
  src/main/java/seedu/address/logic/commands/SwitchCommand.java
  src/main/java/seedu/address/logic/commands/ViewJournalEntryCommand.java
  src/main/java/seedu/address/logic/commands/ViewPersonCommand.java
  src/main/java/seedu/address/logic/parser/AddAliasCommandParser.java
  src/main/java/seedu/address/logic/parser/AddContactCommandParser.java
  src/main/java/seedu/address/logic/parser/AddJournalEntryCommandParser.java
  src/main/java/seedu/address/logic/parser/CheckScheduleCommandParser.java
  src/main/java/seedu/address/logic/parser/DeleteAliasCommandParser.java
  src/main/java/seedu/address/logic/parser/DeleteContactCommandParser.java
  src/main/java/seedu/address/logic/parser/DeleteJournalEntryCommandParser.java
  src/main/java/seedu/address/logic/parser/EditContactCommandParser.java
  src/main/java/seedu/address/logic/parser/EditJournalEntryCommandParser.java
  src/main/java/seedu/address/logic/parser/FindContactCommandParser.java
  src/main/java/seedu/address/logic/parser/FindJournalEntryCommandParser.java
  src/main/java/seedu/address/logic/parser/HelpCommandParser.java
  src/main/java/seedu/address/logic/parser/IntelliJournalParser.java
  src/main/java/seedu/address/logic/parser/Parser.java
  src/main/java/seedu/address/logic/parser/ViewJournalEntryCommandParser.java
  src/main/java/seedu/address/logic/parser/ViewPersonCommandParser.java
  src/test/java/seedu/address/logic/commands/HelpCommandTest.java
  src/test/java/seedu/address/logic/parser/AddAliasCommandParserTest.java
  src/test/java/seedu/address/logic/parser/AddContactCommandParserTest.java
  src/test/java/seedu/address/logic/parser/AddJournalEntryCommandParserTest.java
  src/test/java/seedu/address/logic/parser/CheckScheduleCommandParserTest.java
  src/test/java/seedu/address/logic/parser/CommandParserTestUtil.java
  src/test/java/seedu/address/logic/parser/DeleteAliasCommandParserTest.java
  src/test/java/seedu/address/logic/parser/DeleteContactCommandParserTest.java
  src/test/java/seedu/address/logic/parser/DeleteJournalEntryCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditContactCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditJournalEntryCommandParserTest.java
  src/test/java/seedu/address/logic/parser/FindCommandParserTest.java
  src/test/java/seedu/address/logic/parser/HelpCommandParserTest.java
  src/test/java/seedu/address/logic/parser/IntelliJournalParserTest.java
  src/test/java/seedu/address/logic/parser/ViewJournalEntryCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ViewPersonCommandParserTest.java
Labels: priority.Medium, type.Enhancement

#234 Add ug examples
  docs/UserGuide.md
  docs/images/UGExamples/addcontactExample1.png
  docs/images/UGExamples/addcontactExample2.png
  docs/images/UGExamples/changethemeExample1.png
  docs/images/UGExamples/changethemeExample2.png
  docs/images/UGExamples/clearcExample1.png
  docs/images/UGExamples/clearcExample2.png
  docs/images/UGExamples/deletecExample1.png
  docs/images/UGExamples/deletecExample2.png
  docs/images/UGExamples/editcExample1.png
  docs/images/UGExamples/editcExample2.png
  docs/images/UGExamples/editjExample1.png
  docs/images/UGExamples/editjExample2.png
  docs/images/UGExamples/exitExample.png
  docs/images/UGExamples/findcExample1.png
  docs/images/UGExamples/findcExample2.png
  docs/images/UGExamples/findjExample1.png
  docs/images/UGExamples/findjExample2.png
  docs/images/UGExamples/helpExample2.png
  docs/images/UGExamples/helpExample3.png
  docs/images/UGExamples/listcExample1.png
  docs/images/UGExamples/listcExample2.png
  docs/images/UGExamples/switchExample1.png
  docs/images/UGExamples/switchExample2.png
  docs/team/jazerler.md
  docs/team/nauw1010.md
  src/main/java/seedu/address/logic/parser/FindContactCommandParser.java
Labels: priority.High, type.Enhancement
