Repository AY2021S1-CS2103T-W17-4/tp, pull requests merged in 2020-10, with the labels that each got.

#65 Fix addj message
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/AddJournalEntryCommand.java
  src/main/java/seedu/address/logic/parser/AddJournalEntryCommandParser.java
Labels: type.Bug

#66 Add person uid
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/commons/util/JsonUtil.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddContactCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/model/journal/Date.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JournalStorage.java
  src/main/java/seedu/address/storage/JsonAdaptedEntry.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/storage/JsonJournalStorage.java
  src/main/java/seedu/address/storage/JsonSerializableJournal.java
  src/main/java/seedu/address/storage/Storage.java
  src/main/java/seedu/address/storage/StorageManager.java
  src/test/data/JsonAddressBookStorageTest/invalidAndValidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/parser/AddContactCommandParserTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: priority.High, type.Enhancement

#68 Support journal unit test
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/test/java/seedu/address/model/JournalTest.java
  src/test/java/seedu/address/model/journal/UniqueEntryListTest.java
  src/test/java/seedu/address/testutil/EntryUtil.java
  src/test/java/seedu/address/testutil/TypicalEntries.java
Labels: type.Task

#69 Add tests for logic (parsers, commands and integration tests)
  src/main/java/seedu/address/logic/parser/AddJournalEntryCommandParser.java
  src/main/java/seedu/address/model/journal/Entry.java
  src/test/java/seedu/address/logic/commands/AddJournalEntryCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/AddJournalEntryCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/AddJournalEntryCommandParserTest.java
Labels: priority.High, type.Task

#72 Enhence testing coverage for journal part
  src/test/java/seedu/address/model/journal/DateTest.java
  src/test/java/seedu/address/model/journal/DescriptionTest.java
  src/test/java/seedu/address/model/journal/EntryTest.java
  src/test/java/seedu/address/model/journal/TitleTest.java
  src/test/java/seedu/address/model/journal/UniqueEntryListTest.java
Labels: type.Enhancement

#73 Add tags for JsonAdaptedEntry
  src/main/java/seedu/address/storage/JsonAdaptedEntry.java
Labels: priority.High, type.Enhancement

#78 Add support for tab navigation in commands
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/AddContactCommand.java
  src/main/java/seedu/address/logic/commands/AddJournalEntryCommand.java
  src/main/java/seedu/address/logic/commands/ClearAddressBookCommand.java
  src/main/java/seedu/address/logic/commands/ClearJournalCommand.java
  src/main/java/seedu/address/logic/commands/CommandResult.java
  src/main/java/seedu/address/logic/commands/ListContactCommand.java
  src/main/java/seedu/address/logic/commands/ListJournalEntryCommand.java
  src/main/java/seedu/address/logic/commands/SwitchCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/ClearAddressBookCommandTest.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/ListContactCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
Labels: priority.High, type.Task

#80 View commands for address book and journal
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/ListJournalEntryCommand.java
  src/main/java/seedu/address/logic/commands/ViewCommand.java
  src/main/java/seedu/address/logic/commands/ViewJournalEntryCommand.java
  src/main/java/seedu/address/logic/commands/ViewPersonCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/ViewCommandParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/test/java/seedu/address/logic/commands/AddContactCommandTest.java
  src/test/java/seedu/address/logic/commands/AddJournalEntryCommandTest.java
Labels: type.Task

#91 Add delete contacts and delete journal commands
  src/main/java/seedu/address/logic/commands/DeleteContactCommand.java
  src/main/java/seedu/address/logic/commands/DeleteJournalEntryCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/DeleteContactCommandParser.java
  src/main/java/seedu/address/logic/parser/DeleteJournalEntryCommandParser.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/DeleteContactCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/DeleteContactCommandParserTest.java
Labels: priority.High, type.Task

#92 Fix help command not to switch tab
  src/main/java/seedu/address/logic/commands/CommandResult.java
  src/main/java/seedu/address/logic/commands/HelpCommand.java
  src/main/java/seedu/address/ui/MainWindow.java
Labels: priority.Medium, severity.VeryLow, type.Bug

#93 Update addj to support contacts and tags
  src/main/java/seedu/address/logic/commands/AddJournalEntryCommand.java
  src/main/java/seedu/address/logic/commands/DeleteContactCommand.java
  src/main/java/seedu/address/logic/parser/AddJournalEntryCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/test/java/seedu/address/logic/commands/DeleteContactCommandTest.java
Labels: priority.High, type.Task

#99 Make addc addj takes optional parameters
  src/main/java/seedu/address/logic/parser/AddContactCommandParser.java
  src/main/java/seedu/address/logic/parser/AddJournalEntryCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/journal/Date.java
  src/main/java/seedu/address/model/journal/Description.java
  src/main/java/seedu/address/model/person/Address.java
  src/main/java/seedu/address/model/person/Email.java
  src/main/java/seedu/address/model/person/Phone.java
  src/test/java/seedu/address/logic/parser/AddContactCommandParserTest.java
  src/test/java/seedu/address/logic/parser/AddJournalEntryCommandParserTest.java
  src/test/java/seedu/address/model/journal/DateTest.java
  src/test/java/seedu/address/model/journal/DescriptionTest.java
Labels: priority.High, type.Task

#101 Add storage unit tests
  src/main/java/seedu/address/logic/parser/AddJournalEntryCommandParser.java
  src/main/java/seedu/address/model/Journal.java
  src/main/java/seedu/address/model/journal/Entry.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedEntry.java
  src/main/java/seedu/address/storage/JsonAddressBookStorage.java
  src/main/java/seedu/address/storage/JsonJournalStorage.java
  src/test/data/JsonJournalStorageTest/invalidAndValidEntryJournal.json
  src/test/data/JsonJournalStorageTest/invalidEntryJournal.json
  src/test/data/JsonJournalStorageTest/notJsonFormatJournal.json
  src/test/data/JsonSerializableJournalTest/duplicateEntryJournal.json
  src/test/data/JsonSerializableJournalTest/invalidEntryJournal.json
  src/test/data/JsonSerializableJournalTest/typicalEntriesJournal.json
  src/test/java/seedu/address/model/JournalTest.java
  src/test/java/seedu/address/model/journal/EntryTest.java
  src/test/java/seedu/address/model/journal/UniqueEntryListTest.java
  src/test/java/seedu/address/storage/JsonAdaptedEntryTest.java
  src/test/java/seedu/address/storage/JsonAdaptedTagTest.java
  src/test/java/seedu/address/storage/JsonJournalStorageTest.java
  src/test/java/seedu/address/storage/JsonSerializableAddressBookTest.java
  src/test/java/seedu/address/storage/JsonSerializableJournalTest.java
  src/test/java/seedu/address/testutil/EntryBuilder.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/TypicalEntries.java
Labels: priority.Medium, type.Enhancement

#118 Enhence testing coverage
  src/main/java/seedu/address/model/ModelManager.java
  src/test/java/seedu/address/model/ModelManagerTest.java
Labels: type.Enhancement

#120 V1.3 support command alias
  build.gradle
  src/main/java/seedu/address/logic/commands/ValidCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/model/ModelManager.java
  src/test/java/seedu/address/logic/commands/AddJournalEntryCommandTest.java
  src/test/java/seedu/address/logic/commands/ValidCommandTest.java
Labels: type.Story

#123 V1.3 update DG for command alias
  docs/DeveloperGuide.md
  docs/diagrams/commandAlias/aliasClassDiagram.puml
  docs/diagrams/commandAlias/asliasSequenceDiagram.puml
  docs/images/commandAlias/aliasClassDiagram.png
  docs/images/commandAlias/asliasSequenceDiagram.png
Labels: type.Task

#125 V1.3 support model to edit entry
  src/main/java/seedu/address/model/Journal.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/journal/UniqueEntryList.java
  src/test/java/seedu/address/logic/commands/AddContactCommandTest.java
  src/test/java/seedu/address/logic/commands/AddJournalEntryCommandTest.java
  src/test/java/seedu/address/model/journal/UniqueEntryListTest.java
Labels: type.Task

#126 V1.3 Add check schedule command
  src/main/java/seedu/address/logic/commands/AddJournalEntryCommand.java
  src/main/java/seedu/address/logic/commands/CheckScheduleCommand.java
  src/main/java/seedu/address/logic/commands/ValidCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CheckScheduleCommandParser.java
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/journal/Date.java
  src/test/data/JsonSerializableJournalTest/typicalEntriesJournal.json
  src/test/java/seedu/address/logic/commands/AddJournalEntryCommandTest.java
  src/test/java/seedu/address/logic/commands/CheckScheduleCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/CheckScheduleCommandParserTest.java
  src/test/java/seedu/address/logic/parser/FindCommandParserTest.java
  src/test/java/seedu/address/model/journal/DateTest.java
  src/test/java/seedu/address/storage/JsonJournalStorageTest.java
  src/test/java/seedu/address/storage/JsonSerializableJournalTest.java
  src/test/java/seedu/address/testutil/TypicalEntries.java
Labels: priority.High, type.Story

#127 Update UG find command and DG implementation details for tab navigation
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/tabNavigation/MainWindowTabNavigationActivityDiagram.puml
  docs/images/MainWindowTabNavigationActivityDiagram.png
Labels: type.Task

#129 Update UG to include aliases
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/CheckScheduleActivityDiagram.puml
  docs/diagrams/CheckScheduleSequenceDiagram.puml
  docs/images/CheckScheduleActivityDiagram.png
  docs/images/CheckScheduleSequenceDiagram.png
  src/main/java/seedu/address/logic/commands/ValidCommand.java
  src/main/java/seedu/address/ui/MainWindow.java
Labels: priority.Medium, type.Enhancement

#131 Add assertion to JsonSerializableJournal
  src/main/java/seedu/address/logic/commands/FindContactCommand.java
  src/main/java/seedu/address/logic/parser/AddContactCommandParser.java
  src/main/java/seedu/address/logic/parser/AddJournalEntryCommandParser.java
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
  src/main/java/seedu/address/storage/JsonSerializableJournal.java
Labels: priority.Low, type.Task

#132 Update AddressBookParser to IntelliJournalParser
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/CheckScheduleSequenceDiagram.puml
  docs/diagrams/DeleteSequenceDiagram.puml
  docs/diagrams/HelpSequenceDiagram.puml
  docs/diagrams/UndoSequenceDiagram.puml
  docs/diagrams/commandAlias/aliasClassDiagram.puml
  docs/diagrams/commandAlias/aliasSequenceDiagram.puml
  docs/diagrams/tracing/LogicSequenceDiagram.puml
  docs/images/CheckScheduleSequenceDiagram.png
  docs/images/DeleteSequenceDiagram.png
  docs/images/HelpSequenceDiagram.png
  docs/images/UndoSequenceDiagram.png
  docs/images/commandAlias/aliasClassDiagram.png
  docs/images/commandAlias/aliasSequenceDiagram.png
  docs/images/commandAlias/asliasSequenceDiagram.png
  docs/images/tracing/LogicSequenceDiagram.png
  docs/tutorials/AddRemark.md
  docs/tutorials/TracingCode.md
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/parser/IntelliJournalParser.java
  src/test/java/seedu/address/logic/parser/IntelliJournalParserTest.java
Labels: priority.High, type.Enhancement

#144 Add a dashboard tab with frequent and recent contacts
  README.md
  docs/UserGuide.md
  docs/images/Ui-contacts.png
  docs/images/Ui-dashboard.png
  docs/images/Ui-journal.png
  docs/images/Ui.png
  docs/index.md
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/SwitchCommand.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/journal/Date.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/ui/DashboardTab.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/DashboardTab.fxml
  src/main/resources/view/EntryContent.fxml
  src/main/resources/view/EntryListCard.fxml
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/PersonListCard.fxml
  src/test/java/seedu/address/logic/commands/AddAliasCommandTest.java
  src/test/java/seedu/address/logic/commands/AddContactCommandTest.java
  src/test/java/seedu/address/logic/commands/AddJournalEntryCommandTest.java
  src/test/java/seedu/address/logic/commands/ViewJournalEntryCommandTest.java
  src/test/java/seedu/address/logic/commands/ViewPersonCommandTest.java
Labels: priority.Medium, type.Bug, type.Enhancement, type.Task

#155 Support parse ignore space
  src/main/java/seedu/address/logic/parser/AddAliasCommandParser.java
  src/main/java/seedu/address/logic/parser/IntelliJournalParser.java
Labels: severity.Medium

#159 Standardise message usage
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/AddAliasCommand.java
  src/main/java/seedu/address/logic/commands/AddContactCommand.java
  src/main/java/seedu/address/logic/commands/AddJournalEntryCommand.java
  src/main/java/seedu/address/logic/commands/CheckScheduleCommand.java
  src/main/java/seedu/address/logic/commands/ClearAddressBookCommand.java
  src/main/java/seedu/address/logic/commands/ClearJournalCommand.java
  src/main/java/seedu/address/logic/commands/DeleteContactCommand.java
  src/main/java/seedu/address/logic/commands/DeleteJournalEntryCommand.java
  src/main/java/seedu/address/logic/commands/EditContactCommand.java
  src/main/java/seedu/address/logic/commands/EditJournalEntryCommand.java
  src/main/java/seedu/address/logic/commands/ExitCommand.java
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/commands/FindContactCommand.java
  src/main/java/seedu/address/logic/commands/FindJournalEntryCommand.java
  src/main/java/seedu/address/logic/commands/HelpCommand.java
  src/main/java/seedu/address/logic/commands/ListContactCommand.java
  src/main/java/seedu/address/logic/commands/ListJournalEntryCommand.java
  src/main/java/seedu/address/logic/commands/SwitchCommand.java
  src/main/java/seedu/address/logic/commands/ViewCommand.java
  src/main/java/seedu/address/logic/commands/ViewJournalEntryCommand.java
  src/main/java/seedu/address/logic/commands/ViewPersonCommand.java
  src/main/java/seedu/address/logic/parser/AddAliasCommandParser.java
  src/test/java/seedu/address/logic/commands/AddAliasCommandTest.java
  src/test/java/seedu/address/logic/commands/ClearJournalCommandTest.java
Labels: priority.Medium, severity.Medium, type.Task

#171 Fix the bug with empty content view in contacts and journal
  src/main/java/seedu/address/ui/EntryListPanel.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/PersonListPanel.java
Labels: severity.High, type.Bug
